### ISSUE TITLE
Update of dependencies

### ISSUE THREAD

**Issue by engblom** [juxt/dirwatch#11]
Please, update the dependency from Clojure 1.5.1 to 1.7.0. In my own tests no other changes are needed than the version bump in project.clj.

This makes smaller end application as not both 1.5.1 and 1.7.0 needs to be included in the uberjar.

**Comment by malcolmsparks** [comment]
I've removed the clojure dependency, it will use whatever's in your project.

**Comment by malcolmsparks** [comment]
See release 0.2.3
